[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyhedonic"
version = "0.1.0"
description = "Tools for experimenting with fractional hedonic games."
readme = "README.md"
requires-python = ">=3.12"
license = "GPL-3.0-or-later"

dependencies = [
  "numpy",
  "numba",
  "pydot",
  "pandas",
  "tabulate",
  "networkx",
  "PyYAML",
  "jinja2",
]

[project.optional-dependencies]
dev = ["pytest", "ruff", "docformatter"]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 100

[tool.docformatter]
pre-summary-newline = true
make-summary-multi-line = true
black = true
wrap-summaries = 100
wrap-descriptions = 100
